title: Static Blog
author: Yury Yurevich
url: http://127.0.0.1:8080
default_post_template: post.html
archive_month_template: archive_month.html
archive_year_template: archive_year.html
tag_template: tag.html
